Add snackbar component and stories
DHI-GRAS/react-components-ts pull request #6
Opened 2021-03-30 08:20 UTC by rosudhi

2021-03-31 06:37 UTC, bertearazvan requested changes
Hi Ronald!  Thank you very much for contributing!

While testing your branch out, I have encountered the following:
- I have fetched your PR locally and I have encountered this error when I tried clicking on "Show" in the story docs.
![b3b45b18ab32a9e63475972769fe22c0](https://user-images.githubusercontent.com/30385700/113100030-23e59780-91fb-11eb-8b14-9a7748311868.png)
- While looking through the code, I also notice that there are two stories, could that be merged into one story?
- My ts is throwing the error in `Snackbar.stories.tsx` that `Module '"./types"' has no exported member 'SnackbarProviderProps'.`.
- Please remove any console logs within the code

This is more of a question, when you submitted this PR, were you promoted to follow some PR guidelines? Such as it's described in https://github.com/DHI-GRAS/react-components-ts/blob/add-lab/.github/PULL_REQUEST_TEMPLATE.md - just wonder if it works or it was just omitted?

Thank you and sorry if the list is too specific :) Feel free to comment on these

2021-03-31 08:26 UTC, rosudhi commented
> Hi Ronald! Thank you very much for contributing!
> 
> While testing your branch out, I have encountered the following:
> 
> * I have fetched your PR locally and I have encountered this error when I tried clicking on "Show" in the story docs.
>   ![b3b45b18ab32a9e63475972769fe22c0](https://user-images.githubusercontent.com/30385700/113100030-23e59780-91fb-11eb-8b14-9a7748311868.png)
> * While looking through the code, I also notice that there are two stories, could that be merged into one story?
> * My ts is throwing the error in `Snackbar.stories.tsx` that `Module '"./types"' has no exported member 'SnackbarProviderProps'.`.
> * Please remove any console logs within the code
> 
> This is more of a question, when you submitted this PR, were you promoted to follow some PR guidelines? Such as it's described in https://github.com/DHI-GRAS/react-components-ts/blob/add-lab/.github/PULL_REQUEST_TEMPLATE.md - just wonder if it works or it was just omitted?
> 
> Thank you and sorry if the list is too specific :) Feel free to comment on these

Ah, i think that stories created automatically, perhaps because i'm using snackbar.default.stories name instead of snackbar.stories.
yes, i followed the guidlines.

2021-03-31 09:14 UTC, rihr requested changes
👍 
All files that should be importable in the parent project need to be imported, exported in the index file, as seen here
https://github.com/rosudhi/react-components-ts/blob/add-lab/packages/react-components-lab/src/index.ts

I will disable the react/require-default-props and react/jsx-props-no-spreading rules in the eslintrc, so the comments disabling them in files won't be necessary

2021-03-31 09:14 UTC, rihr commented on packages/react-components-lab/src/components/Snackbar/SnackbarProvider.tsx
> +          }
This could have probably be split up above, making it more readable and not having to ignore the no-nested-ternary rule

Example:
```js
const stateAutoHideDuration = state.options?.autoHideDuration
const existingAutoHideDuration = existingSnackbarProps.autoHideDuration
const hasStateOptions = state.options && stateAutoHideDuration
const existingAutoHideDuration ? existingAutoHideDuration : DEFAULT_DURATION

const autoHideDuration = hasStateOptions ? stateAutoHideDuration : existingAutoHideDuration
```
same for the TransitionComponent prop

2021-03-31 09:14 UTC, rihr commented on packages/react-components-lab/src/components/Snackbar/DefaultSnackbar.tsx
> +/* eslint-disable react/jsx-props-no-spreading */
I should have disabled these rules in the eslintrc, will do that

2021-03-31 09:19 UTC, rihr commented
I've disabled the eslint rules now https://github.com/DHI-GRAS/react-components-ts/commit/7bf391bfa6ac7a0a99088b7beff03cf988880fda

2021-04-06 07:27 UTC, rihr approved these changes

2021-04-06 07:29 UTC, bertearazvan approved these changes

2021-04-06 09:38 UTC, rihr commented
@rosudhi I'm guessing you don't have permission to merge it. Should I merge it, or did you plan on adding any more changes?

2021-04-06 10:11 UTC, rosudhi commented
> @rosudhi I'm guessing you don't have permission to merge it. Should I merge it, or did you plan on adding any more changes?
you're right, i don't have that. yes, merge it please, no plan in near future. i will make new PR for new component or features later

2021-04-06 10:12 UTC, merged